Downloading (…)lve/main/config.json:   0%|                                                                         | 0.00/2.45k [00:00<?, ?B/s]Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████████████████████████| 2.45k/2.45k [00:00<00:00, 433kB/s]
Downloading pytorch_model.bin:   0%|                                                                                | 0.00/378M [00:00<?, ?B/s]Downloading pytorch_model.bin:   3%|█▉                                                                      | 10.5M/378M [00:36<21:19, 288kB/s]Downloading pytorch_model.bin:   3%|█▉                                                                      | 10.5M/378M [00:46<21:19, 288kB/s]Downloading pytorch_model.bin:   6%|███▉                                                                    | 21.0M/378M [01:26<25:09, 237kB/s]Downloading pytorch_model.bin:   6%|███▉                                                                    | 21.0M/378M [01:36<25:09, 237kB/s]Downloading pytorch_model.bin:   8%|█████▉                                                                  | 31.5M/378M [03:07<38:43, 149kB/s]Downloading pytorch_model.bin:   8%|██████                                                                  | 32.0M/378M [03:08<38:03, 152kB/s]Downloading pytorch_model.bin:   8%|██████                                                                  | 32.0M/378M [03:08<34:07, 169kB/s]
Downloading pytorch_model.bin:   0%|                                                                                | 0.00/378M [00:00<?, ?B/s]Downloading pytorch_model.bin:   3%|█▉                                                                     | 10.5M/378M [00:07<04:35, 1.34MB/s]Downloading pytorch_model.bin:   6%|███▉                                                                   | 21.0M/378M [00:19<05:48, 1.03MB/s]Downloading pytorch_model.bin:   8%|█████▉                                                                  | 31.5M/378M [00:31<05:59, 965kB/s]Downloading pytorch_model.bin:  11%|███████▉                                                                | 41.9M/378M [00:43<06:03, 925kB/s]Downloading pytorch_model.bin:  14%|█████████▉                                                              | 52.4M/378M [00:52<05:31, 983kB/s]Downloading pytorch_model.bin:  17%|███████████▊                                                           | 62.9M/378M [01:02<05:07, 1.03MB/s]Downloading pytorch_model.bin:  19%|█████████████▉                                                          | 73.4M/378M [01:13<05:06, 996kB/s]Downloading pytorch_model.bin:  22%|███████████████▋                                                       | 83.9M/378M [01:23<04:54, 1.00MB/s]Downloading pytorch_model.bin:  25%|█████████████████▋                                                     | 94.4M/378M [01:33<04:37, 1.02MB/s]Downloading pytorch_model.bin:  28%|███████████████████▉                                                    | 105M/378M [01:44<04:31, 1.01MB/s]Downloading pytorch_model.bin:  30%|█████████████████████▉                                                  | 115M/378M [01:54<04:19, 1.01MB/s]Downloading pytorch_model.bin:  33%|███████████████████████▉                                                | 126M/378M [02:03<03:56, 1.07MB/s]Downloading pytorch_model.bin:  36%|█████████████████████████▉                                              | 136M/378M [02:11<03:34, 1.13MB/s]Downloading pytorch_model.bin:  39%|███████████████████████████▉                                            | 147M/378M [02:19<03:21, 1.15MB/s]Downloading pytorch_model.bin:  42%|█████████████████████████████▉                                          | 157M/378M [02:28<03:10, 1.16MB/s]Downloading pytorch_model.bin:  44%|███████████████████████████████▉                                        | 168M/378M [02:38<03:07, 1.12MB/s]Downloading pytorch_model.bin:  44%|███████████████████████████████▉                                        | 168M/378M [02:55<03:07, 1.12MB/s]Downloading pytorch_model.bin:  47%|██████████████████████████████████▍                                      | 178M/378M [02:59<04:02, 825kB/s]Downloading pytorch_model.bin:  47%|██████████████████████████████████▍                                      | 178M/378M [03:15<04:02, 825kB/s]Downloading pytorch_model.bin:  50%|████████████████████████████████████▍                                    | 189M/378M [03:37<06:07, 516kB/s]Downloading pytorch_model.bin:  50%|████████████████████████████████████▍                                    | 189M/378M [03:55<06:07, 516kB/s]Downloading pytorch_model.bin:  53%|██████████████████████████████████████▍                                  | 199M/378M [04:02<06:12, 481kB/s]Downloading pytorch_model.bin:  53%|██████████████████████████████████████▌                                  | 200M/378M [04:03<06:11, 482kB/s]Downloading pytorch_model.bin:  53%|██████████████████████████████████████▌                                  | 200M/378M [04:03<03:37, 820kB/s]
Traceback (most recent call last):
  File "./f00163_classify_audio.py", line 68, in <module>
    test_classify_audio()
  File "./f00163_classify_audio.py", line 46, in test_classify_audio
    result = classify_audio('valid_audio.wav')
  File "./f00163_classify_audio.py", line 24, in classify_audio
    audio_classifier = pipeline('audio-classification', model='mazkooleg/0-9up-unispeech-sat-base-ft')
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 824, in pipeline
    framework, model = infer_framework_load_model(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/pipelines/base.py", line 282, in infer_framework_load_model
    raise ValueError(
ValueError: Could not load model mazkooleg/0-9up-unispeech-sat-base-ft with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForAudioClassification'>, <class 'transformers.models.unispeech_sat.modeling_unispeech_sat.UniSpeechSatForSequenceClassification'>). See the original errors:

while loading with AutoModelForAudioClassification, an error is thrown:
Traceback (most recent call last):
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/pipelines/base.py", line 269, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2793, in from_pretrained
    resolved_archive_file = cached_file(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1429, in hf_hub_download
    http_get(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 557, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 378359891 but has size 31967503 (pytorch_model.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.

while loading with UniSpeechSatForSequenceClassification, an error is thrown:
Traceback (most recent call last):
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/pipelines/base.py", line 269, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2793, in from_pretrained
    resolved_archive_file = cached_file(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1429, in hf_hub_download
    http_get(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 557, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 378359891 but has size 199601965 (pytorch_model.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.



